travis:
  secure:
    BINSTAR_TOKEN: KkyXeNVj2QjDKx+lGD52AiyWe21sKK1pWO7BsM2kDNHhnyLy46AeZLKGNJT0vBYqvf8aoS81sfY5uGqVAudkORMWHnJAovylfvCRSfaYpKM/uWMz2JyCyIw+ktKD9nAcAVpRCgn8bKly1eGlzKw/oX/ogQVnAq9m0ICu/BEYgfwmxRgHYTcwgvJqLoQ7p+G4J3Vsk7BLLRMf1al6qXSdsFlyO+TPedFzVja4LNmkA7SUpQn8wXANIquFZDVRsV4/TW8admnKRaE/TNoiQGPNIUZcOWoUG5UyOrIWurEYSAOtmomPx6ABTqg1IZBoLfygNZ9oWTEeFxAOlMOtT6id9454tcaS2WJcO7kJ/+HnvuMWjzIRuNOFQhKBjmxr091N8hgkKwjTSQbGiuL97Z6y3dxdAXTMobHTigmTH4IyM0lHCZy/auobebFC2EVWMevA1Y3aJAAMPkP3Ht5mBcvM5CmJwtyNrCsbdmRWVePlAiaB9jkw8o6BmpDM07wx5JTQv7kMdDyXs15+tELgprzp0qPi7q13cZ2SBBkw8q7yEpHEAe406mtTL7awCMs/FumFB9PvgtmHqJkObnsYxXgwVfqGVw+4StST8KNPiRGLlJhZn1FHMr/F5SYKSU6V8v36iNKtBvuMqUYWtLbUkls21vAGIDAB61NgJgz/u0cLJ8U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
